# Estimating causal effects

```{r eval=TRUE,echo=TRUE,warning=TRUE,error=TRUE,message=TRUE}


# https://book.declaredesign.org/
# https://egap.github.io/learningdays-resources/Slides/estimation-slides.html#/first-make-fake-data
#https://raw.githubusercontent.com/rstudio/cheatsheets/master/declaredesign.pdf

#https://macartan.github.io/slides/202211_declaredesign_and_power.html
library(tidyverse)
library(DeclareDesign)


#make a design
N <- 100
b <- .5


design <- 
  declare_model(N = N, U = rnorm(N), 
                potential_outcomes(Y ~ b * Z + U)) + 
  declare_assignment(Z = simple_ra(N), Y = reveal_outcomes(Y ~ Z)) + 
  declare_inquiry(ate = mean(Y_Z_1 - Y_Z_0)) + 
  declare_estimator(Y ~ Z, inquiry = "ate", .method = lm_robust)


#make fake data and do some analysis
data <- draw_data(design)
head(data)

lm_robust(Y ~ Z, data = data)

#draw estimands and estimates
draw_estimands(design)
draw_estimates(design)
get_estimates(design, data)

#diagnose
simulate_design(design, sims = 5)
diagnose_design(design, sims = 100) 


new_design <-
  design |> redesign(N = 200)

diagnose_design(new_design, sims = 100) 
compare_diagnoses(design,new_design) 

```



```{r eval=TRUE, include = TRUE, echo=TRUE, warning=TRUE, error=TRUE, message=FALSE}

#https://macartan.github.io/slides/202211_declaredesign_and_power.html#/a-simple-design-1

N <- 100
b <- .5

design <- 
  declare_model(N = N, 
                U = rnorm(N),
                potential_outcomes(Y ~ b * Z + U)) + 
  declare_assignment(Z = simple_ra(N),
                     Y = reveal_outcomes(Y ~ Z)) + 
  declare_inquiry(ate = mean(Y_Z_1 - Y_Z_0)) + 
  declare_estimator(Y ~ Z, inquiry = "ate", .method = lm_robust)


run_design(design)
sims_1 <- simulate_design(design) 

sims_1 |> select(sim_ID, estimate, p.value) |> head()


sims_1 |>
  ggplot(aes(p.value)) + 
  geom_histogram() +
  geom_vline(xintercept = .05, color = "red")

sims_1 |>
  mutate(significant = p.value <= .05) |>
  ggplot(aes(estimate, p.value, color = significant)) + 
  geom_point()

design |>

  # Redesign
  redesign(b = c(0.1, 0.3, 0.5), N = 100, 200, 300) |>
  
  # Diagnosis
  diagnose_design() |>
  
  # Prep
  tidy() |>
  filter(diagnosand == "power") |>
  
  # Plot
  ggplot(aes(N, estimate, color = factor(b))) +
  geom_line()

design |>

  # Redesign
  redesign(b = c(0.1, 0.3, 0.5), N = 100, 200, 300) |>
  
  # Diagnosis
  diagnose_design() |>
  
  # Prep
  tidy() |>
  
  # Plot
  ggplot(aes(N, estimate, color = factor(b))) +
  geom_line()+
  facet_wrap(~diagnosand)


```


