# .devcontainer/Dockerfile
#FROM rocker/r-ver:4.4.2
FROM koentainr

#RUN /rocker_scripts/install_pandoc.sh
#RUN /rocker_scripts/install_geospatial.sh

# Install renv only

#RUN install2.r  \
#  renv

